### ISSUE TITLE
Fallos en la interacciones del portal

### ISSUE THREAD

**Issue by fgalan** [manucarrace/gn#119]
Las iteracciones sobre el portal tienen algunos defectos. A continuación un resumen de ellos:

1. Por lo que parece, cuanto el atributo tiene metadata, estos se muestran en la celdas como un JSON. El comportamiento correcto sería mostrar solo el valor, ignorando el metadata. (En general, recordemos que la idea es ser respetuoso con los metadata si existen, pero no mostrarlos ni manipularlos en el portal). **<-- FIXED**
2. No se borrar los quick filters entre transiciones. Pe. cuando se hace click en el filter de la izquierda, todos los quick filters deberían de desaparecer. Si no, es engañoso para el usuario, porque ve un quick filter que no se está aplicando. **<-- FIXED**
3. Si caduca el token (i.e. se reciben 401 en alguna petición a la plataforma) ha de volverse inmediatamente a la pantalla de login. **<-- FIXED**
4. No se muestras correctamente alguno de los campos de las celdas cuando hay caracteres especiales (pe. acentos). **<-- NTC (tras investigarlo, no es un problema del portal realmente, sino de los datos de entrada con los que se han poblado las entidades)**
5. Al hacer el export de la tabla sni filtrar (404) ha ocurrido un error que ha hecho cascar el portal (hasta que le he dado al F5 para refrescar no se ha recuperado). Se me ocurren dos posibles alternativas que estén pasado: **<-- he vuelto a probar con otro entorno de browser y ahora no consigo reproducirlo**
    * Errores 500 en el CB que no están siendo correctamente capturados en la lógica del export y provocan el casque
    * Que un conjunto de ~10000 entidades con >200 campos cada una se le esté atragantando al portal a la hora de generar el fichero CSV
6. No aplicar el uppercase a nombres de vistas, filtros o formatos. Que aparecan con los names tal cual el usuario los ha definido. **<-- FIXED**
7. Navegando por la paginación cuando había solo 2 páginas (es decir, sin entrar en el problema de los 500 que podría devolver el CB) se ha observado este error en las trazas de firebug: **<-- FIXED (al menos ya no consigor reproducirlo)**

```
TypeError: can't assign to properties of (new String("")): not an object
Traza de la pila:
setStyles@http://localhost:8083/app/components/listEntities/controller/listEntitiesController.js:183:40
getData/<@http://localhost:8083/app/components/listEntities/controller/listEntitiesController.js:216:17
getData@http://localhost:8083/app/components/listEntities/controller/listEntitiesController.js:194:13
success@http://localhost:8083/app/components/listEntities/controller/listEntitiesController.js:290:31
h/<@http://localhost:8083/vendor/angular/angular.min.js:137:167
Of/this.$get</m.prototype.$digest@http://localhost:8083/vendor/angular/angular.min.js:148:130
Of/this.$get</m.prototype.$apply@http://localhost:8083/vendor/angular/angular.min.js:151:353
l@http://localhost:8083/vendor/angular/angular.min.js:103:165
t@http://localhost:8083/vendor/angular/angular.min.js:108:228
yg/</A.onload@http://localhost:8083/vendor/angular/angular.min.js:109:139
 Possibly unhandled rejection: {}
```

**Comment by fgalan** [comment]
8. Que el intro dispare filtro rápido

**Comment by fgalan** [comment]
PR de arreglos: https://github.com/manucarrace/gn/pull/120

**Comment by arubiogfi** [comment]
PR de arreglos:
#124 
#125

**Comment by josecarlosaparicio** [comment]
#127

**Comment by fgalan** [comment]
9. Elminar el `&` final en el box de filtro
10. No mostrar `?` cuando no hay filtro. Usar un token estilo "<sin filtro>" cuando ocurra esto.

**Comment by fgalan** [comment]
11. Problema con las transiciones cuando se crea una vista nueva. Hay algún tipo glitch que hace que la vista nueva quede cargada con los datos de la vieja o algo así (ya lo comentó Iván en una review, pero parece que persiste).
12. Debería de usarse "Georelación" en vez de "Geolocalización" en 

![imagen](https://user-images.githubusercontent.com/1534240/37209261-e94734ac-23a4-11e8-9731-4c374fbbc063.png)

**Comment by arubiogfi** [comment]
PR puntos 9 y 10
#137

**Comment by arubiogfi** [comment]
PR punto 6:
#138

**Comment by fgalan** [comment]
PR punto 11: https://github.com/manucarrace/gn/pull/141
