### ISSUE TITLE
Creción de filtro/formato a partir de otro

### ISSUE THREAD

**Issue by fgalan** [manucarrace/gn#132]
Ahora mismo se puede modificar un filtro y crear un filtro nuevo, pero estaría bien convinar ambas funcionalidades.

Es decir un botón "Nuevo a partir de" para crear un filtro como alternativa a "Nuevo", que muestre el formulario de creación pero rellenado a partir de los datos del filtro sobre el que se pulsó el botón.

**Comment by JuanPiedehierro** [comment]
La solución en la que estamos pensando, es la siguiente:

Situarte en el filtro deseado, y pulsar la opción de modificar. Entonces aparecerán tres botones: modificar | guardar como | cancelar. Las nueva funcionalidad de forma visual sería:

![prototipo_pr_132](https://user-images.githubusercontent.com/35959705/37706809-1a7042d4-2d01-11e8-8c2a-429d7efb44e8.jpg)

**Comment by fgalan** [comment]
Como solución a este issue me parece bien, pero ojo, que este issue no es de los prioritarios para este sprint. Revisar planificación y, en caso de dudas, consultarme en privado.

**Comment by fgalan** [comment]
Implementado en PR https://github.com/manucarrace/gn/pull/178
