### ISSUE TITLE
Formato condicional: rangos dinámicos

### ISSUE THREAD

**Issue by fgalan** [manucarrace/gn#134]
Ahora mismo podemos definir formatos condicionales por rangos, pero los valores que los delimitan son fijos, eg:

```
[0, 10, 50, 100]
```
Sería deseable poder definir los umbrales en función del valor de un atributo de la entidad, dentro de dicho formato. Pe, tengo un los atributos "umbral1" y "umbral2", cuyo valor puede ser distinto en cada entidad, y aplico un formato:

```
[0, "${umbral1}", "${umbral2}", 100]
```

Si la entidad (fila) E1 tiene umbral1=10 y umbral2=40 esto se traducirá en la práctica en:

```
[0, 10, 40, 100]
```

Si la entidad (fila) E2 tiene umbral1=40 y umbral2=80 esto se traducirá en la práctica en:

```
[0, 40, 80, 100]
```

**Comment by fgalan** [comment]
El ejemplo que hemos hablado por skype:

```
...
{
  "name": "fillLevel",
  "op": "dynamic-range",  // "op": "range",
  "value": [0, 3.51, "threholdFillLevelLow", "thresholdFillLevelHigh", 7.1],
  "style": ["{background:'MediumSeaGreen', 'border':'2px solid Black'}",
  "{background:'orange', 'border':'2px solid Black'}",
  "{background:'red', 'border':'2px solid Black'}",
  "{background:'black', color: 'white', 'border':'2px solid White'}"]
 }
...
```

Table:

```
id, type, fillLevel,    threholdFillLevelLow, thresholdFillLevelHigh
E1  T     4 (naranja)   5                     7
E2  T     5 (red)       4                     10
```

**Comment by arubiogfi** [comment]
Una duda que me acaba de surgir, ¿entiendo que los atributos sobre los que se quiere medir el rango siempre tienen que ir en el formato no? En caso contrario, al momento de aplicar estilo no tengo esos valores.

Y por otro lado, ¿me fío de que el orden siempre va a ser correcto, o queréis que aplique un orden al array que resulte?

Es decir, el ejemplo E2, va de 4 a 19 y el array quedaría así: [0, 3.51, 4, 10, 7.1] y lo lógico es  [0, 3.51, 4, 7.1, 10]

**Comment by fgalan** [comment]
> Una duda que me acaba de surgir, ¿entiendo que los atributos sobre los que se quiere medir el rango siempre tienen que ir en el formato no? En caso contrario, al momento de aplicar estilo no tengo esos valores.

El front tendría que comprobar en tiempo de creación/edición que para todo rango dinámico que haya en el formato, todos los umbrales que se expresen con atributos tienen dicho atributo como parte del formato. En el ejemplo anterior habría que comprobar que `threholdFillLevelLow` y  `thresholdFillLevelHigh` están como formatos (i.e. buscar los `name` correctos en el array JSON que representa el formato).

En primera derivada, si se complica mucho hacer esta comprobación, márcalo con un TODO como deuda en el código a donde aplique y se hace más adelante.

> Y por otro lado, ¿me fío de que el orden siempre va a ser correcto, o queréis que aplique un orden al array que resulte?

Esto es más complicado de comprobar, porque en tiempo de creación/modificación del formato no sabes los valores, dependerá del "runtime" de la consulta al CB. Lo que se podría hacer (es un check sencillo) es comprobar que el array resultante está ordenado y, si no lo está entonces se suprime el estilo condicional para en esa celda.

**Comment by fgalan** [comment]
Implementado en PR https://github.com/manucarrace/gn/pull/164
