### ISSUE TITLE
Internacionalizacion/extracción de literales en el FE

### ISSUE THREAD

**Issue by fgalan** [manucarrace/gn#18]
Basado en:

```
    "angular-i18n": "^1.5.8",
    "angular-translate": "^2.12.1",
```

Estarían como opciones un fichero solo con todos los lenguajes o un fichero json por cada lenguaje. Lo segundo sería lo más limpio.

**Comment by arubiogfi** [comment]
La documentación se encuentra aquí: https://angular-translate.github.io

El ejemplo que viene es así: 

`$translateProvider.translations('en', {
    TITLE: 'Hello',
    FOO: 'This is a paragraph.',
    BUTTON_LANG_EN: 'english',
    BUTTON_LANG_DE: 'german'
  });
  $translateProvider.translations('de', {
    TITLE: 'Hallo',
    FOO: 'Dies ist ein Paragraph.',
    BUTTON_LANG_EN: 'englisch',
    BUTTON_LANG_DE: 'deutsch'
  });
  $translateProvider.preferredLanguage('en');
});`

Entiendo que permitirá llamar un fichero para cada idioma, tengo que revisarlo.
Como nomenclatura de cada fichero sería tipo _language_es_ES.json_

**Comment by fgalan** [comment]
La resolución de este issue resolvería un par de TODOs introducidos en la PR #14

```
<!-- TODO -> Change message by content in configuration file -->
```

**Comment by fgalan** [comment]
La PR https://github.com/manucarrace/gn/pull/112 proporciona una primera implementación del framework que se usará. Faltan más PRs ahora para ir cambiando los distintos ficheros pendientes.

**Comment by fgalan** [comment]
La PR https://github.com/manucarrace/gn/pull/118 completa el trabajo de estracción de cadenas. Cerramos issue.
