### ISSUE TITLE
Implementación básica de formatos

### ISSUE THREAD

**Issue by fgalan** [manucarrace/gn#23]
Sobre la implementación base de la tabla (issue #3) este issue contemplaría la implementación de formatos, tanto su gestión estilo bookmark (creación, guardado en DB, edición, borrado, etc.) así como su uso efectivo en la petición contra el CB.

"Como administrador del servicio quiero porde gestionar los formatos. Se deberán poder crear y guardar, modificar y borrar formatos"

"Como administrador del servicio quiero poder aplicar formatos al listado de entidades"

El formato será una lista de atributos separada por coma y se aplicará tal cual al valor de `attrs=` a la hora de hacer la query al CB, eg.:

```
GET /v2/entities?<parte_correspondiente_al_filtro>&attrs=attr1,attr2,att3
```

**Comment by mrutid** [comment]
Es importante tener en cuenta que a futuro estos formatos evolucionaran para incluir:

Estilo de celdas (Color, tamaño...)

Posteriormente aparecera el concepto de Estilo condicional (aplicar Estilo "true" o Estilo "false").

Tambien apareceran formularios y controles para la gestion/validación/construcción asistida de formatos (lo mismo que pasará con los flitros).

**Comment by fgalan** [comment]
La funcionalidad básica se considera implementada y por tanto este issue es cerrable. Spin-off y deuda de la funcionalidad podría aparecer como issues a parte.
