### ISSUE TITLE
Export a CSV

### ISSUE THREAD

**Issue by fgalan** [manucarrace/gn#24]
Sobre la implementación base de la tabla (issue #3) este issue contemplaría la exportación a formato CSV

"Como administrador del servicio quiero poder exportar a formato csv el listado de entidades con el filtro aplicado"

Esta exportación ha de contemplar el filtro *filtros* y *formatos*. 

* El *filtro* determinará que entidades han de exportarse (es decir, las filas del CSV)
* El *formato* determinará que atributos y en que orden se exportan (es decir, que columnas incluir y en que orden en el CSV). El id y type de entidad (que no forman parte del formato) se devuelven siempre como primera y segunda columna.

Filtro y formatos son opcionales:

* Si no se especifica filtro, el CSV incluirá todas las entidades en el CB
* Si no se especifica formato, el CSV incluirá los atributos en el orden que los haya devuelto el CB

La exportación no tiene en cuenta la paginación. Es decir, lo que determina las entidades a exportar es el filtro, pero no se pagina sobre le conjunto de resultados que determine el filtro y se devuelven todos ellos.

**Comment by mrutid** [comment]
En la exportación ha de tenerse en cuenta la paginación con el fin de recuperar las entidades en batches (el tamaño de batch debe ser configurable)

**Comment by fgalan** [comment]
Funcionalidad básica implementada en PR #36, pero issue aun abierto en espera de probar/cubrir la funcionalidad para casos de ficheros realmente grandes (pe. 1GB). En tal caso, igual hace falta usar algún tipo de técnica de streaming/pipelining para volcar los datos al fichero.

**Comment by fgalan** [comment]
El export ha de considerar el formato utilizado por el Portal de la plataforma:

> La primera fila debe corresponderse con la fila de cabecera, que debe contener:
>*    entityID
>*    entityType
>*    nombre de atributo 1 < tipo de atributo 1 >
>*    nombre de atributo 2 < tipo de atributo 2 >
>*    ...
>*    nombre de atributo X < tipo de atributo X >

**Comment by fgalan** [comment]
La PR https://github.com/manucarrace/gn/pull/62 trabaja una mejor alternativa para esta feature, usando un servicio de backend para generar el CSV. Habría que analizarla, frente a otras altenrativas (pe. pipelining/streaming a fichero en el FE).

**Comment by fgalan** [comment]
Ajustes a la exporta para incluir el tipo de atributo entre `<...>` en PR #74

**Comment by josecarlosaparicio** [comment]
Para solventar el problema de la exportación de ficheros muy grandes y no dejar colgado el navegador en una posible implementación desde el lado del cliente únicamente, las escrituras deben hacerse directamente al disco duro. Sin embargo, las distintas posibilidades de escribir información desde el navegador (persistent storage) son limitadas:
 - No existe un estándar común para todos los navegadores, 
 - Puede presentarse inconvenientes relativos a seguridad
 - Las implementaciones de los navegadores son experimentales, obsoletas o no existen. 
 - El estándar propuesto [API Writer]((https://www.w3.org/TR/file-writer-api/)) por W3C está abandonado 

Actualmente existe el siguiente panorama:
 - Sólo compatible para **Chrome**: [FileSystem](https://developer.mozilla.org/es/docs/Web/API/FileSystem) / [LocalFileSystem](https://caniuse.com/#search=filesystem) / [FileWriter](https://www.html5rocks.com/es/tutorials/file/filesystem/#toc-file-writing)
 (Experimental); [BlobBuilder](https://developer.mozilla.org/es/docs/Web/API/BlobBuilder) (Deprecated) 
- Sólo compatible para **Firefox**: [FileHandle API](https://developer.mozilla.org/en-US/docs/Web/API/File_Handle_API) (Experimental) 
- Para **IE** (No Edge): Debe estudiarse el obsoleto ActiveX.
- **Safari**: No se ha encontrado.

Alternativas que quedan directamente descartadas son el uso de localStorage, sessionStorage e IndexedDB por su extremada limitación de espacio de 8MB.

**Comment by fgalan** [comment]
Tras la reunión de revisión de hoy, esto sería lo pendiente en esta funcionalidad. Por un lado, una serie de **flecos**:

* Utilizar `entityID` para la columna que representa el id de la entidad
* Utilizar `entityType` para la columna que representa el type de la entidad
* Utilizar `,` como separador y `"` para quote (i.e. todo lo que esté entre quotes se condiera un mismo campo, aunque el separador `,` aparezca entre ellas), e.g:

```
entityId,entityType,field1<string>,field2<string>
device1,device,texto1,"text2,text3"
```

en este caso field2 = text2,text3

Puede surgir la duda de que ocurre si `"` aparece entre los caracteres del campo. En ese caso, se escapa con `""`, eg:

```
entityId,entityType,field1<object>
device1,device,texto1,"{""a"": 1}"
```

en este caso field1 = {"a": 1}. Aunque en principio este caso no creo que se dé en este desarrollo.

Es posible que esta forma de funcionar sea bastante estándar y que sea cosa de encontrar la librería adecuada de Node que la implemente. Pe, en Python funciona como comento más arriba: https://docs.python.org/2/library/csv.html

Todos los cambios anteriores tendrían su cambio asociado también en la funcionalidad de import para que el round-trip export+import funcione.

**Comment by fgalan** [comment]
Por otro lado, en lo relativo al **refactoring para enganchar la funcionalidad con la de SFTP** (https://github.com/manucarrace/gn/issues/107) podemos plantearlo de la siguiente manera:

* Existirá un servicio de backend que genera el CSV (pe. `generateCsv()` o mejor nombre que se os ocurra) y lo devuelve como respuesta. La lógica actual de generación que usa el front end se movería desde donde está ahora a dicho servicio.
* Cuando el usuario pulsa el botón "CSV" de la GUI, el frontal invoca a `getnerateCsv()` y sirve el resultado como un fichero que el usuario grabará donde quiera.
* Cuanto el usuario pulse el (nuevo) botón "Exportar a SFTP" de la GUI el frontal invocará un servicio de backend `exportToSFTP()` el cual se basará en `generarteCsv()` para la generación.

Me preocupa que el tamaño del CVS resultante pueda hacer inviable este diseño. Igual en una primera implementación no afecta, pero no lo perdamos de vista.

**Comment by fgalan** [comment]
Una librería que podría usarse para el import/export es https://www.npmjs.com/package/ya-csv

**Comment by josecarlosaparicio** [comment]
Sobre utilizar la librería ya-csv, he visto que sólo trabaja sobre streams y en node. Habría que analizar si es posible integrarla tanto para el frontal de cara a hacer las importaciones, como para el nuevo servicio backend de exportación.

**Comment by josecarlosaparicio** [comment]
Para el envío de csv al sftp, propongo utilizar https://github.com/mscdex/ssh2-streams

**Comment by fgalan** [comment]
> Sobre utilizar la librería ya-csv, he visto que sólo trabaja sobre streams y en node

Con el refactor, al final la generación del CSV se haría en el backend (con lo que no importa que solo esté en node). Lo de que trabaje sobre streams, si el stream puede asociarse al flujo que luego se envía por SFTP o al que se le envía al frontend igual resolvemos el tema de los tamaños grandes y matamos dos pájaros de un tiro.

...o igual no. No me he mirado la librearía :), pero igual lo que digo puede tener algún sentido.

**Comment by fgalan** [comment]
> Con el refactor, al final la generación del CSV se haría en el backend (con lo que no importa que solo esté en node.

...ahora que caigo, igual la funcionalidad de importación si que la necesitaría en el frontend.

**Comment by fgalan** [comment]
La PR #62 finalizaría este tema, con la realización del export en el backend.
