### ISSUE TITLE
Importación de CSV

### ISSUE THREAD

**Issue by fgalan** [manucarrace/gn#74]
Descripción como user story: "Como administrador del servicio quiero poder modificar varias entidades de forma masiva a través de fichero csv".

Consideraciones a tener en cuenta:

* Los CSV obtenidos mediante la funcionalidad de export (ya implementada) deberán ser importables mediante esta funcionalidad.
* Teniendo en cuenta lo anterior, la funcionalidad de export debería de incluir la generación del tipo de los atributos (descrito aquí: https://github.com/manucarrace/gn/issues/24#issuecomment-366734867). Observar que las columnas `id` y `type` en el CSV no usan tal `<...>` puesto que el concepto de tipo de atributos no aplica a estos campos.
* Teniendo en cuenta que el fichero CSV puede ser muy grande, la creación de entidades debería hacerse por batches. En ese sentido, utilizar la operación `POST /v2/op/update` descrita en la spec de NGSIv2 en http://telefonicaid.github.io/fiware-orion/api/v2/stable/. El actionType a utilizar debería ser "APPEND".
* Sobre el tamaño del batch, caben dos alternativas: 1) prefijar un número de entidades (en una constante del front) como tamaño de batch, 2) prefijar un tamaño de payload (en una constante de front) como tamaño de batch. El segundo approach sería el óptimo (ya que no es lo mismo una entidad que tiene 1 solo atributo que otra que tiene 200) pero igual es más díficil de implementar.

**Comment by josecarlosaparicio** [comment]
En la segunda alternativa para limitar las subidas, con la variable tamaño del payload, ¿Qué se está limitando, el número de caracteres (length) del objeto enviado?

**Comment by fgalan** [comment]
Sí, el algoritmo podría ser algo así (pseudocódigo):

```
while csv.hasMoreRows():
   var entitiesVector
   while entieisVector.size < BATCH_SIZE_LIMIT && csv.hasMoreRows():
      entitiesVector.addNextRow
   entitiesVector.send()
   entitiesVector.clear()
```

**Comment by fgalan** [comment]
Implementado por PR https://github.com/manucarrace/gn/pull/92
