### ISSUE TITLE
Medidor de progreso en import/export de CSV

### ISSUE THREAD

**Issue by fgalan** [manucarrace/gn#98]
Introducir el típico medidor de progreso (0%... 10%... 50%...) en los procesos de import/export, el cual, en función del número de filas ya importada/exportadas vaya cambiando.

**Comment by josecarlosaparicio** [comment]
El caso de importación ya está implementado e incluido en master a través de la PR #92.

**Comment by fgalan** [comment]
Para el download el propio navegador muestra un control de descarga que se mueve y muestra actividad. Por tanto, la podemos considerar como cerrada.
